In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['Row1','Row2','Row3','Row4','Row5'],columns=['Colum1','Colum2','Colum3','Colum4'])

In [9]:
df.head()

      Colum1  Colum2  Colum3  Colum4
Row1       0       1       2       3
Row2       4       5       6       7
Row3       8       9      10      11
Row4      12      13      14      15
Row5      16      17      18      19

In [11]:
df.to_csv('Test1.csv')

In [13]:
df.loc['Row1']

Colum1    0
Colum2    1
Colum3    2
Colum4    3
Name: Row1, dtype: int32

In [15]:
type(df.loc['Row1'])

pandas.core.series.Series

In [19]:
df.iloc[:,0]

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Colum1, dtype: int32

In [21]:
type(df.iloc[:,0])

pandas.core.series.Series

In [23]:
df.iloc[:,:2]

      Colum1  Colum2
Row1       0       1
Row2       4       5
Row3       8       9
Row4      12      13
Row5      16      17

In [25]:
type(df.iloc[:,:2])

pandas.core.frame.DataFrame

In [29]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
df['Colum1'].value_counts()

Colum1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [35]:
df.isnull().sum()

Colum1    0
Colum2    0
Colum3    0
Colum4    0
dtype: int64

In [37]:
df['Colum1'].unique()

array([ 0,  4,  8, 12, 16])

In [41]:
type(df['Colum1'])
##row d

pandas.core.series.Series